### ISSUE TITLE
When Moving to collision area, game crashes

### ISSUE THREAD

**Issue by griotdonation** [RafaelBarbosatec/turn_game#1]
Hi Rafael,

I hope you're well. Im finding an issue the crashes the turn game. There is code which collects a list of components which contains collision, and if the tile contains collision do not display a "gridCanMove" box on UI. But im seeing the there is moveable tiles that shoudlnt be due to collision, and when i click on it, the game freezes. 

![image](https://user-images.githubusercontent.com/55745803/204106054-dd837a7e-66a7-4a61-a640-18fdc5ba4234.png)

**Comment by RafaelBarbosatec** [comment]
Fixed in the last update to Bonfire 3.0
